language: ruby
rvm:
- 2.2.3
script: bundle exec rake test
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
notifications:
  slack:
    secure: e3c4luCB9ePLaHB13PdNpR8/QGKlxBpe0VJglAsk4G0OoUw/YsA3ij/wAElMzRu+WQypQ560OJk3FJxdeGSTES2SvC18ugVeJuqJlj09ex1EDzADFxYSqq5TGjByIwxwy48kuLlMrb2nR51ioRqvsCt+SxfgBJYmwfuB9IaozlkxMiF373EG5wXsnz6kSZhJ94MaLcz4bzbJUD7rPYJlcJ1+E13oJngoY+tDaYM1fIFnZ7mGIR7Dw/k7viaQJ2232a81EQ/Wyxph2syvCcLmVWBS0kZAfgls8ttHWKMxlH9FD/EuFawGvnlAwqvof73b+xqUA0GOFX9GrwGg4lc2WsxWQfNbUJmVUIn1gB9L7H6foHuzVthEYPHDVEp2JR34rlXq2Pe2JgY0+IHBSyMjy9FEyVUntH0AB6DwpJ7QWw0sTBVgngXp7w96+ELNHIGOnQovfsHnxjemrOHZdhJZJ2lHK5Y8SfRfNKFptvgnmHtAlJ3TPoYwJaagfZQUzs9r0H1xDS1XDuGVcuQFSs90emI5SL8ZfANDFinkwntN58miOZ72oMpQrZX9jI49BXGARfxZKG3C3PFVjwSlal7Jzf725ja8IxWQl8g2i+SSPa1VciruheXnSBHjpK1UB/BLKOG0En/zdARvHU2wwrRNB4roamReLq/ktbMkk1pUk28=
  email:
  - PhoneGapCI@adobe.com
